/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hust.soict.cnpm.group24.view;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author ADMIN
 */
public class AddFeeScreen extends javax.swing.JFrame {

    /**
     * Creates new form AddFeeScreen
     */
    public AddFeeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo_panel = new javax.swing.JPanel();
        logo_label = new javax.swing.JLabel();
        manipulating_panel = new javax.swing.JPanel();
        tieu_de_label = new javax.swing.JLabel();
        ma_ho_label = new javax.swing.JLabel();
        ma_phi_label = new javax.swing.JLabel();
        ten_phi_label = new javax.swing.JLabel();
        ngay_nop_label = new javax.swing.JLabel();
        ma_ho_field = new javax.swing.JTextField();
        so_tien_field = new javax.swing.JTextField();
        enter_pay_button = new javax.swing.JButton();
        so_tien_label = new javax.swing.JLabel();
        ten_phi_field = new javax.swing.JTextField();
        ma_phi_select_button = new javax.swing.JButton();
        ma_ho_select_button = new javax.swing.JButton();
        ma_phi_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_panel.setBackground(new java.awt.Color(67, 85, 133));

        logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hust/soict/cnpm/group24/icon/Blue Manager-logos_white.png"))); // NOI18N

        javax.swing.GroupLayout logo_panelLayout = new javax.swing.GroupLayout(logo_panel);
        logo_panel.setLayout(logo_panelLayout);
        logo_panelLayout.setHorizontalGroup(
            logo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo_panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(logo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        logo_panelLayout.setVerticalGroup(
            logo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo_panelLayout.createSequentialGroup()
                .addComponent(logo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(logo_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        manipulating_panel.setBackground(new java.awt.Color(255, 255, 255));
        manipulating_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tieu_de_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tieu_de_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tieu_de_label.setText("THÊM GIAO DỊCH MỚI");
        manipulating_panel.add(tieu_de_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 221, 38));

        ma_ho_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ma_ho_label.setText("Mã hộ");
        manipulating_panel.add(ma_ho_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 123, 40));

        ma_phi_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ma_phi_label.setText("Mã phí");
        manipulating_panel.add(ma_phi_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 123, 40));

        ten_phi_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ten_phi_label.setText("Tên phí:");
        manipulating_panel.add(ten_phi_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 123, 40));

        ngay_nop_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ngay_nop_label.setText("Ngày nộp");
        manipulating_panel.add(ngay_nop_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 123, 40));

        ma_ho_field.setEditable(false);
        ma_ho_field.setBackground(new java.awt.Color(255, 255, 255));
        ma_ho_field.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manipulating_panel.add(ma_ho_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 154, 40));

        so_tien_field.setEditable(false);
        so_tien_field.setBackground(new java.awt.Color(255, 255, 255));
        so_tien_field.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manipulating_panel.add(so_tien_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 154, 40));

        enter_pay_button.setBackground(new java.awt.Color(129, 143, 180));
        enter_pay_button.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        enter_pay_button.setText("THÊM");
        enter_pay_button.setFocusable(false);
        enter_pay_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enter_pay_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enter_pay_buttonMouseExited(evt);
            }
        });
        manipulating_panel.add(enter_pay_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 181, 50));

        so_tien_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        so_tien_label.setText("Số tiền cần nộp:");
        manipulating_panel.add(so_tien_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 123, 40));

        ten_phi_field.setEditable(false);
        ten_phi_field.setBackground(new java.awt.Color(255, 255, 255));
        ten_phi_field.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manipulating_panel.add(ten_phi_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 154, 40));

        ma_phi_select_button.setText("Chọn");
        ma_phi_select_button.setFocusable(false);
        ma_phi_select_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ma_phi_select_buttonActionPerformed(evt);
            }
        });
        manipulating_panel.add(ma_phi_select_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 60, 40));

        ma_ho_select_button.setText("Chọn");
        ma_ho_select_button.setFocusable(false);
        ma_ho_select_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ma_ho_select_buttonActionPerformed(evt);
            }
        });
        manipulating_panel.add(ma_ho_select_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 60, 40));

        ma_phi_field.setEditable(false);
        ma_phi_field.setBackground(new java.awt.Color(255, 255, 255));
        ma_phi_field.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manipulating_panel.add(ma_phi_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 154, 40));

        getContentPane().add(manipulating_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 400, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enter_pay_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter_pay_buttonMouseEntered
        // TODO add your handling code here:
        enter_pay_button.setBackground(new Color(245,232,199));
    }//GEN-LAST:event_enter_pay_buttonMouseEntered

    private void enter_pay_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter_pay_buttonMouseExited
        // TODO add your handling code here:
        enter_pay_button.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_enter_pay_buttonMouseExited

    private void ma_ho_select_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ma_ho_select_buttonActionPerformed
        // TODO add your handling code here:
        AddFee_SelectMaHoScreen addFee_SelectMaHoScreen = new AddFee_SelectMaHoScreen();
        addFee_SelectMaHoScreen.setParentContext(this);
        addFee_SelectMaHoScreen.setVisible(true);
    }//GEN-LAST:event_ma_ho_select_buttonActionPerformed

    private void ma_phi_select_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ma_phi_select_buttonActionPerformed
        // TODO add your handling code here:
        AddFee_SelectMaPhiScreen addFee_SelectMaPhiScreen = new AddFee_SelectMaPhiScreen();
        addFee_SelectMaPhiScreen.setParentContext(this);
        addFee_SelectMaPhiScreen.setVisible(true);
    }//GEN-LAST:event_ma_phi_select_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showAddFee() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFeeScreen().setVisible(true);
            }
        });
    }

    public JButton getEnter_pay_button() {
        return enter_pay_button;
    }

    public void setEnter_pay_button(JButton enter_pay_button) {
        this.enter_pay_button = enter_pay_button;
    }

    public JLabel getLogo_label() {
        return logo_label;
    }

    public void setLogo_label(JLabel logo_label) {
        this.logo_label = logo_label;
    }

    public JPanel getLogo_panel() {
        return logo_panel;
    }

    public void setLogo_panel(JPanel logo_panel) {
        this.logo_panel = logo_panel;
    }

    public JTextField getMa_ho_field() {
        return ma_ho_field;
    }

    public void setMa_ho_field(JTextField ma_ho_field) {
        this.ma_ho_field = ma_ho_field;
    }

    public JLabel getMa_ho_label() {
        return ma_ho_label;
    }

    public void setMa_ho_label(JLabel ma_ho_label) {
        this.ma_ho_label = ma_ho_label;
    }

    public JButton getMa_ho_select_button() {
        return ma_ho_select_button;
    }

    public void setMa_ho_select_button(JButton ma_ho_select_button) {
        this.ma_ho_select_button = ma_ho_select_button;
    }

    public JTextField getMa_phi_field() {
        return ma_phi_field;
    }

    public void setMa_phi_field(JTextField ma_phi_field) {
        this.ma_phi_field = ma_phi_field;
    }

    public JLabel getMa_phi_label() {
        return ma_phi_label;
    }

    public void setMa_phi_label(JLabel ma_phi_label) {
        this.ma_phi_label = ma_phi_label;
    }

    public JButton getMa_phi_select_button() {
        return ma_phi_select_button;
    }

    public void setMa_phi_select_button(JButton ma_phi_select_button) {
        this.ma_phi_select_button = ma_phi_select_button;
    }

    public JPanel getManipulating_panel() {
        return manipulating_panel;
    }

    public void setManipulating_panel(JPanel manipulating_panel) {
        this.manipulating_panel = manipulating_panel;
    }

    public JLabel getNgay_nop_label() {
        return ngay_nop_label;
    }

    public void setNgay_nop_label(JLabel ngay_nop_label) {
        this.ngay_nop_label = ngay_nop_label;
    }

    public JTextField getSo_tien_field() {
        return so_tien_field;
    }

    public void setSo_tien_field(JTextField so_tien_field) {
        this.so_tien_field = so_tien_field;
    }

    public JLabel getSo_tien_label() {
        return so_tien_label;
    }

    public void setSo_tien_label(JLabel so_tien_label) {
        this.so_tien_label = so_tien_label;
    }

    public JTextField getTen_phi_field() {
        return ten_phi_field;
    }

    public void setTen_phi_field(JTextField ten_phi_field) {
        this.ten_phi_field = ten_phi_field;
    }

    public JLabel getTen_phi_label() {
        return ten_phi_label;
    }

    public void setTen_phi_label(JLabel ten_phi_label) {
        this.ten_phi_label = ten_phi_label;
    }

    public JLabel getTieu_de_label() {
        return tieu_de_label;
    }

    public void setTieu_de_label(JLabel tieu_de_label) {
        this.tieu_de_label = tieu_de_label;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enter_pay_button;
    private javax.swing.JLabel logo_label;
    private javax.swing.JPanel logo_panel;
    private javax.swing.JTextField ma_ho_field;
    private javax.swing.JLabel ma_ho_label;
    private javax.swing.JButton ma_ho_select_button;
    private javax.swing.JTextField ma_phi_field;
    private javax.swing.JLabel ma_phi_label;
    private javax.swing.JButton ma_phi_select_button;
    private javax.swing.JPanel manipulating_panel;
    private javax.swing.JLabel ngay_nop_label;
    private javax.swing.JTextField so_tien_field;
    private javax.swing.JLabel so_tien_label;
    private javax.swing.JTextField ten_phi_field;
    private javax.swing.JLabel ten_phi_label;
    private javax.swing.JLabel tieu_de_label;
    // End of variables declaration//GEN-END:variables
}
