/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hust.soict.cnpm.group24.view;

import javax.swing.*;
import java.awt.*;
import static java.awt.Color.yellow;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ADMIN
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form mainscreen
     */
    //ImageIcon icon = new ImageIcon("Search_Icon.png");
    
    public MainScreen() {
        initComponents();
        show_ho_so_panel.setVisible(false);
        show_khoan_phi_panel.setVisible(false);
        show_ho_khau_panel.setVisible(false);
        show_nhan_khau_panel.setVisible(false);
        show_home_panel.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        show_panel = new javax.swing.JPanel();
        show_home_panel = new javax.swing.JPanel();
        bm_name_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        show_ho_khau_panel = new javax.swing.JPanel();
        tt_ho_khau_panel = new javax.swing.JPanel();
        tt_ho_khau_label = new javax.swing.JLabel();
        searching_ho_khau_field = new javax.swing.JTextField();
        searching_ho_khau_button = new javax.swing.JButton();
        searching_ho_khau_question_label = new javax.swing.JLabel();
        searching_ho_khau_type_box = new javax.swing.JComboBox<>();
        ho_khau_scroll_pane = new javax.swing.JScrollPane();
        ho_khau_table = new javax.swing.JTable();
        sua_tt_ho_khau_panel = new javax.swing.JPanel();
        sua_tt_ho_khau_label = new javax.swing.JLabel();
        them_tt_ho_khau_panel = new javax.swing.JPanel();
        them_tt_ho_khau_label = new javax.swing.JLabel();
        xoa_tt_ho_khau_panel = new javax.swing.JPanel();
        xoa_tt_ho_khau_label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        show_nhan_khau_panel = new javax.swing.JPanel();
        searching_nhan_khau_field = new javax.swing.JTextField();
        searching_nhan_khau_button = new javax.swing.JButton();
        searching_nhan_khau_question_label = new javax.swing.JLabel();
        searching_nhan_khau_type_box = new javax.swing.JComboBox<>();
        sua_tt_nhan_khau_panel = new javax.swing.JPanel();
        sua_tt_nhan_khau_label = new javax.swing.JLabel();
        them_tt_nhan_khau_panel = new javax.swing.JPanel();
        them_tt_nhan_khau_label = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        nhan_khau_table = new javax.swing.JTable();
        xoa_tt_nhan_khau_panel = new javax.swing.JPanel();
        xoa_tt_nhan_khau_label = new javax.swing.JLabel();
        tt_nhan_khau_panel = new javax.swing.JPanel();
        tt_nhan_khau_label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        show_ho_so_panel = new javax.swing.JPanel();
        ql_tk_panel = new javax.swing.JPanel();
        ql_tk_label = new javax.swing.JLabel();
        searching_tai_khoan_field = new javax.swing.JTextField();
        searching_tai_khoan_button = new javax.swing.JButton();
        searching_tai_khoan_question_label = new javax.swing.JLabel();
        searching_tai_khoan_type_box = new javax.swing.JComboBox<>();
        them_tai_khoan_panel = new javax.swing.JPanel();
        them_tai_khoan_label = new javax.swing.JLabel();
        xoa_tai_khoan_panel = new javax.swing.JPanel();
        xoa_tai_khoan_label = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tai_khoan_table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        show_thu_phi_panel = new javax.swing.JPanel();
        tt_giao_dich_panel = new javax.swing.JPanel();
        tt_giao_dich_label = new javax.swing.JLabel();
        searching_thu_phi_type_box = new javax.swing.JComboBox<>();
        searching_thu_phi_question_label = new javax.swing.JLabel();
        searching_thu_phi_field = new javax.swing.JTextField();
        searching_thu_phi_button = new javax.swing.JButton();
        them_giao_dich_panel = new javax.swing.JPanel();
        them_giao_dich_label = new javax.swing.JLabel();
        show_khoan_phi_panel = new javax.swing.JPanel();
        tt_khoan_phi_panel = new javax.swing.JPanel();
        tt_khoan_phi_label = new javax.swing.JLabel();
        searching_khoan_phi_field = new javax.swing.JTextField();
        searching_khoan_phi_button = new javax.swing.JButton();
        searching_khoan_phi_question_label = new javax.swing.JLabel();
        searching_khoan_phi_type_box = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        menu_panel = new javax.swing.JPanel();
        nhan_khau_bt_panel = new javax.swing.JPanel();
        nhan_khau_bt_label = new javax.swing.JLabel();
        ho_khau_bt_panel = new javax.swing.JPanel();
        ho_khau_bt_label = new javax.swing.JLabel();
        ho_so_bt_panel = new javax.swing.JPanel();
        ho_so_bt_label = new javax.swing.JLabel();
        home_bt_panel = new javax.swing.JPanel();
        home_bt_label = new javax.swing.JLabel();
        khoan_phi_bt_panel = new javax.swing.JPanel();
        khoan_phi_bt_label = new javax.swing.JLabel();
        dang_xuat_bt_panel = new javax.swing.JPanel();
        dang_xuat_bt_label = new javax.swing.JLabel();
        thu_phi_bt_panel = new javax.swing.JPanel();
        thu_phi_bt_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blue Manager");
        setBounds(new java.awt.Rectangle(0, 0, 900, 560));
        setResizable(false);

        show_panel.setLayout(new java.awt.CardLayout());

        show_home_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bm_name_label.setFont(new java.awt.Font("STLiti", 1, 30)); // NOI18N
        bm_name_label.setForeground(new java.awt.Color(255, 255, 255));
        bm_name_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bm_name_label.setText("BLUE MOON  - BLUE CITY - BLUE PEOPLE");
        show_home_panel.add(bm_name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 690, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/moon.jpg"))); // NOI18N
        show_home_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 496));

        show_panel.add(show_home_panel, "card2");

        show_ho_khau_panel.setBackground(new java.awt.Color(255, 255, 255));
        show_ho_khau_panel.setForeground(new java.awt.Color(255, 255, 255));
        show_ho_khau_panel.setAlignmentX(0.0F);
        show_ho_khau_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tt_ho_khau_panel.setBackground(new java.awt.Color(67, 85, 133));

        tt_ho_khau_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tt_ho_khau_label.setForeground(new java.awt.Color(255, 255, 255));
        tt_ho_khau_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tt_ho_khau_label.setText("THÔNG TIN HỘ KHẨU");

        javax.swing.GroupLayout tt_ho_khau_panelLayout = new javax.swing.GroupLayout(tt_ho_khau_panel);
        tt_ho_khau_panel.setLayout(tt_ho_khau_panelLayout);
        tt_ho_khau_panelLayout.setHorizontalGroup(
            tt_ho_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tt_ho_khau_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tt_ho_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        tt_ho_khau_panelLayout.setVerticalGroup(
            tt_ho_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tt_ho_khau_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tt_ho_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        show_ho_khau_panel.add(tt_ho_khau_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        searching_ho_khau_field.setText("Tìm kiếm theo mã hộ khẩu");
        searching_ho_khau_field.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searching_ho_khau_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searching_ho_khau_fieldMouseClicked(evt);
            }
        });
        show_ho_khau_panel.add(searching_ho_khau_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 213, 40));

        searching_ho_khau_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search_Icon.png"))); // NOI18N
        searching_ho_khau_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searching_ho_khau_buttonActionPerformed(evt);
            }
        });
        show_ho_khau_panel.add(searching_ho_khau_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 40, 40));

        searching_ho_khau_question_label.setText("Bạn muốn tìm kiếm theo:");
        show_ho_khau_panel.add(searching_ho_khau_question_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 134, 40));

        searching_ho_khau_type_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã hộ khẩu", "Số nhân khẩu", " " }));
        searching_ho_khau_type_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searching_ho_khau_type_boxActionPerformed(evt);
            }
        });
        show_ho_khau_panel.add(searching_ho_khau_type_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 150, 40));

        ho_khau_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A01", "Tùng", "20210001", " "},
                {"A02", "Trung", "20210002", " "},
                {"B01", "Tú", "20210003", " "},
                {null, " ", " ", " "}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ho_khau_scroll_pane.setViewportView(ho_khau_table);

        show_ho_khau_panel.add(ho_khau_scroll_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 560, 300));

        sua_tt_ho_khau_panel.setBackground(new java.awt.Color(129, 143, 180));
        sua_tt_ho_khau_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sua_tt_ho_khau_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sua_tt_ho_khau_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sua_tt_ho_khau_panelMousePressed(evt);
            }
        });

        sua_tt_ho_khau_label.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        sua_tt_ho_khau_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sua_tt_ho_khau_label.setText("Sửa");

        javax.swing.GroupLayout sua_tt_ho_khau_panelLayout = new javax.swing.GroupLayout(sua_tt_ho_khau_panel);
        sua_tt_ho_khau_panel.setLayout(sua_tt_ho_khau_panelLayout);
        sua_tt_ho_khau_panelLayout.setHorizontalGroup(
            sua_tt_ho_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sua_tt_ho_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        sua_tt_ho_khau_panelLayout.setVerticalGroup(
            sua_tt_ho_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sua_tt_ho_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        show_ho_khau_panel.add(sua_tt_ho_khau_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, -1, 40));

        them_tt_ho_khau_panel.setBackground(new java.awt.Color(129, 143, 180));
        them_tt_ho_khau_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                them_tt_ho_khau_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                them_tt_ho_khau_panelMouseExited(evt);
            }
        });

        them_tt_ho_khau_label.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        them_tt_ho_khau_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        them_tt_ho_khau_label.setText("Thêm");

        javax.swing.GroupLayout them_tt_ho_khau_panelLayout = new javax.swing.GroupLayout(them_tt_ho_khau_panel);
        them_tt_ho_khau_panel.setLayout(them_tt_ho_khau_panelLayout);
        them_tt_ho_khau_panelLayout.setHorizontalGroup(
            them_tt_ho_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(them_tt_ho_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        them_tt_ho_khau_panelLayout.setVerticalGroup(
            them_tt_ho_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(them_tt_ho_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        show_ho_khau_panel.add(them_tt_ho_khau_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, 40));

        xoa_tt_ho_khau_panel.setBackground(new java.awt.Color(129, 143, 180));
        xoa_tt_ho_khau_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xoa_tt_ho_khau_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xoa_tt_ho_khau_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                xoa_tt_ho_khau_panelMousePressed(evt);
            }
        });

        xoa_tt_ho_khau_label.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        xoa_tt_ho_khau_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xoa_tt_ho_khau_label.setText("Xóa");

        javax.swing.GroupLayout xoa_tt_ho_khau_panelLayout = new javax.swing.GroupLayout(xoa_tt_ho_khau_panel);
        xoa_tt_ho_khau_panel.setLayout(xoa_tt_ho_khau_panelLayout);
        xoa_tt_ho_khau_panelLayout.setHorizontalGroup(
            xoa_tt_ho_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xoa_tt_ho_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        xoa_tt_ho_khau_panelLayout.setVerticalGroup(
            xoa_tt_ho_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xoa_tt_ho_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        show_ho_khau_panel.add(xoa_tt_ho_khau_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        show_ho_khau_panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, -1, 70));

        show_panel.add(show_ho_khau_panel, "card3");

        show_nhan_khau_panel.setBackground(new java.awt.Color(255, 255, 255));
        show_nhan_khau_panel.setAlignmentX(0.0F);
        show_nhan_khau_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searching_nhan_khau_field.setText("Tìm kiếm theo họ và tên");
        searching_nhan_khau_field.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searching_nhan_khau_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searching_nhan_khau_fieldMouseClicked(evt);
            }
        });
        show_nhan_khau_panel.add(searching_nhan_khau_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 213, 40));

        searching_nhan_khau_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search_Icon.png"))); // NOI18N
        searching_nhan_khau_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searching_nhan_khau_buttonActionPerformed(evt);
            }
        });
        show_nhan_khau_panel.add(searching_nhan_khau_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 40, 40));

        searching_nhan_khau_question_label.setText("Bạn muốn tìm kiếm theo:");
        show_nhan_khau_panel.add(searching_nhan_khau_question_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 134, 40));

        searching_nhan_khau_type_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Họ và tên", "CCCD", "Số điện thoại", "Mã hộ khẩu", " " }));
        searching_nhan_khau_type_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searching_nhan_khau_type_boxActionPerformed(evt);
            }
        });
        show_nhan_khau_panel.add(searching_nhan_khau_type_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 150, 40));

        sua_tt_nhan_khau_panel.setBackground(new java.awt.Color(129, 143, 180));
        sua_tt_nhan_khau_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sua_tt_nhan_khau_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sua_tt_nhan_khau_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sua_tt_nhan_khau_panelMousePressed(evt);
            }
        });

        sua_tt_nhan_khau_label.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        sua_tt_nhan_khau_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sua_tt_nhan_khau_label.setText("Sửa");

        javax.swing.GroupLayout sua_tt_nhan_khau_panelLayout = new javax.swing.GroupLayout(sua_tt_nhan_khau_panel);
        sua_tt_nhan_khau_panel.setLayout(sua_tt_nhan_khau_panelLayout);
        sua_tt_nhan_khau_panelLayout.setHorizontalGroup(
            sua_tt_nhan_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sua_tt_nhan_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        sua_tt_nhan_khau_panelLayout.setVerticalGroup(
            sua_tt_nhan_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sua_tt_nhan_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        show_nhan_khau_panel.add(sua_tt_nhan_khau_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, -1, 40));

        them_tt_nhan_khau_panel.setBackground(new java.awt.Color(129, 143, 180));
        them_tt_nhan_khau_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                them_tt_nhan_khau_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                them_tt_nhan_khau_panelMouseExited(evt);
            }
        });

        them_tt_nhan_khau_label.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        them_tt_nhan_khau_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        them_tt_nhan_khau_label.setText("Thêm");

        javax.swing.GroupLayout them_tt_nhan_khau_panelLayout = new javax.swing.GroupLayout(them_tt_nhan_khau_panel);
        them_tt_nhan_khau_panel.setLayout(them_tt_nhan_khau_panelLayout);
        them_tt_nhan_khau_panelLayout.setHorizontalGroup(
            them_tt_nhan_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(them_tt_nhan_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        them_tt_nhan_khau_panelLayout.setVerticalGroup(
            them_tt_nhan_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(them_tt_nhan_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        show_nhan_khau_panel.add(them_tt_nhan_khau_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, 40));

        nhan_khau_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"20210001", "Hoàng Quang Tùng", "A01", "0382469108"},
                {"20210002", "Phạm Tuấn Trung", "A02", "0987654321"},
                {"20210003", "Vũ Đức Lương", "B01", "0912345678"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(nhan_khau_table);
        if (nhan_khau_table.getColumnModel().getColumnCount() > 0) {
            nhan_khau_table.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        show_nhan_khau_panel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 560, 300));

        xoa_tt_nhan_khau_panel.setBackground(new java.awt.Color(129, 143, 180));
        xoa_tt_nhan_khau_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xoa_tt_nhan_khau_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xoa_tt_nhan_khau_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                xoa_tt_nhan_khau_panelMousePressed(evt);
            }
        });

        xoa_tt_nhan_khau_label.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        xoa_tt_nhan_khau_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xoa_tt_nhan_khau_label.setText("Xóa");

        javax.swing.GroupLayout xoa_tt_nhan_khau_panelLayout = new javax.swing.GroupLayout(xoa_tt_nhan_khau_panel);
        xoa_tt_nhan_khau_panel.setLayout(xoa_tt_nhan_khau_panelLayout);
        xoa_tt_nhan_khau_panelLayout.setHorizontalGroup(
            xoa_tt_nhan_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xoa_tt_nhan_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        xoa_tt_nhan_khau_panelLayout.setVerticalGroup(
            xoa_tt_nhan_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xoa_tt_nhan_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        show_nhan_khau_panel.add(xoa_tt_nhan_khau_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, -1, -1));

        tt_nhan_khau_panel.setBackground(new java.awt.Color(67, 85, 133));

        tt_nhan_khau_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tt_nhan_khau_label.setForeground(new java.awt.Color(255, 255, 255));
        tt_nhan_khau_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tt_nhan_khau_label.setText("THÔNG TIN NHÂN KHẨU");

        javax.swing.GroupLayout tt_nhan_khau_panelLayout = new javax.swing.GroupLayout(tt_nhan_khau_panel);
        tt_nhan_khau_panel.setLayout(tt_nhan_khau_panelLayout);
        tt_nhan_khau_panelLayout.setHorizontalGroup(
            tt_nhan_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tt_nhan_khau_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tt_nhan_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        tt_nhan_khau_panelLayout.setVerticalGroup(
            tt_nhan_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tt_nhan_khau_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tt_nhan_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        show_nhan_khau_panel.add(tt_nhan_khau_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        show_nhan_khau_panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, -1, 70));

        show_panel.add(show_nhan_khau_panel, "card4");

        show_ho_so_panel.setBackground(new java.awt.Color(255, 255, 255));
        show_ho_so_panel.setMinimumSize(new java.awt.Dimension(730, 600));
        show_ho_so_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ql_tk_panel.setBackground(new java.awt.Color(67, 85, 133));

        ql_tk_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ql_tk_label.setForeground(new java.awt.Color(255, 255, 255));
        ql_tk_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ql_tk_label.setText("QUẢN LÝ TÀI KHOẢN");

        javax.swing.GroupLayout ql_tk_panelLayout = new javax.swing.GroupLayout(ql_tk_panel);
        ql_tk_panel.setLayout(ql_tk_panelLayout);
        ql_tk_panelLayout.setHorizontalGroup(
            ql_tk_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ql_tk_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ql_tk_label, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        ql_tk_panelLayout.setVerticalGroup(
            ql_tk_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ql_tk_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ql_tk_label, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        show_ho_so_panel.add(ql_tk_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        searching_tai_khoan_field.setText("Tìm kiếm theo họ và tên");
        searching_tai_khoan_field.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searching_tai_khoan_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searching_tai_khoan_fieldMouseClicked(evt);
            }
        });
        show_ho_so_panel.add(searching_tai_khoan_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 213, 40));

        searching_tai_khoan_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search_Icon.png"))); // NOI18N
        searching_tai_khoan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searching_tai_khoan_buttonActionPerformed(evt);
            }
        });
        show_ho_so_panel.add(searching_tai_khoan_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 40, 40));

        searching_tai_khoan_question_label.setText("Bạn muốn tìm kiếm theo:");
        show_ho_so_panel.add(searching_tai_khoan_question_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 134, 40));

        searching_tai_khoan_type_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Họ và tên", "Tài khoản", "Mật khẩu", " ", " " }));
        searching_tai_khoan_type_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searching_tai_khoan_type_boxActionPerformed(evt);
            }
        });
        show_ho_so_panel.add(searching_tai_khoan_type_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 150, 40));

        them_tai_khoan_panel.setBackground(new java.awt.Color(129, 143, 180));
        them_tai_khoan_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                them_tai_khoan_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                them_tai_khoan_panelMouseExited(evt);
            }
        });

        them_tai_khoan_label.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        them_tai_khoan_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        them_tai_khoan_label.setText("Thêm");

        javax.swing.GroupLayout them_tai_khoan_panelLayout = new javax.swing.GroupLayout(them_tai_khoan_panel);
        them_tai_khoan_panel.setLayout(them_tai_khoan_panelLayout);
        them_tai_khoan_panelLayout.setHorizontalGroup(
            them_tai_khoan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(them_tai_khoan_label, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        them_tai_khoan_panelLayout.setVerticalGroup(
            them_tai_khoan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(them_tai_khoan_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        show_ho_so_panel.add(them_tai_khoan_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, -1, 40));

        xoa_tai_khoan_panel.setBackground(new java.awt.Color(129, 143, 180));
        xoa_tai_khoan_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xoa_tai_khoan_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xoa_tai_khoan_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                xoa_tai_khoan_panelMousePressed(evt);
            }
        });

        xoa_tai_khoan_label.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        xoa_tai_khoan_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xoa_tai_khoan_label.setText("Xóa");

        javax.swing.GroupLayout xoa_tai_khoan_panelLayout = new javax.swing.GroupLayout(xoa_tai_khoan_panel);
        xoa_tai_khoan_panel.setLayout(xoa_tai_khoan_panelLayout);
        xoa_tai_khoan_panelLayout.setHorizontalGroup(
            xoa_tai_khoan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xoa_tai_khoan_label, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        xoa_tai_khoan_panelLayout.setVerticalGroup(
            xoa_tai_khoan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xoa_tai_khoan_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        show_ho_so_panel.add(xoa_tai_khoan_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, -1, -1));

        tai_khoan_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Hoàng Quang Tùng", "TungA01", "123"},
                {"Phạm Trung", "Trungcutecc", "123"},
                {"Khương", "hehehe", "123"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane4.setViewportView(tai_khoan_table);

        show_ho_so_panel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 560, 300));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        show_ho_so_panel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, -1, 70));

        show_panel.add(show_ho_so_panel, "card5");

        show_thu_phi_panel.setBackground(new java.awt.Color(255, 255, 255));
        show_thu_phi_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tt_giao_dich_panel.setBackground(new java.awt.Color(67, 85, 133));

        tt_giao_dich_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tt_giao_dich_label.setForeground(new java.awt.Color(255, 255, 255));
        tt_giao_dich_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tt_giao_dich_label.setText("THÔNG TIN GIAO DỊCH");

        javax.swing.GroupLayout tt_giao_dich_panelLayout = new javax.swing.GroupLayout(tt_giao_dich_panel);
        tt_giao_dich_panel.setLayout(tt_giao_dich_panelLayout);
        tt_giao_dich_panelLayout.setHorizontalGroup(
            tt_giao_dich_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tt_giao_dich_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tt_giao_dich_label, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        tt_giao_dich_panelLayout.setVerticalGroup(
            tt_giao_dich_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tt_giao_dich_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tt_giao_dich_label, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        show_thu_phi_panel.add(tt_giao_dich_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        searching_thu_phi_type_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên chủ hộ", "Mã hộ khẩu", "Mã nhân khẩu", "Mã phí", "Tên phí", " " }));
        searching_thu_phi_type_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searching_thu_phi_type_boxActionPerformed(evt);
            }
        });
        show_thu_phi_panel.add(searching_thu_phi_type_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 150, 40));

        searching_thu_phi_question_label.setText("Bạn muốn tìm kiếm theo:");
        show_thu_phi_panel.add(searching_thu_phi_question_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 134, 40));

        searching_thu_phi_field.setText("Tìm kiếm theo tên chủ hộ");
        searching_thu_phi_field.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searching_thu_phi_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searching_thu_phi_fieldMouseClicked(evt);
            }
        });
        show_thu_phi_panel.add(searching_thu_phi_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 213, 40));

        searching_thu_phi_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search_Icon.png"))); // NOI18N
        searching_thu_phi_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searching_thu_phi_buttonActionPerformed(evt);
            }
        });
        show_thu_phi_panel.add(searching_thu_phi_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 40, 40));

        them_giao_dich_panel.setBackground(new java.awt.Color(129, 143, 180));
        them_giao_dich_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                them_giao_dich_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                them_giao_dich_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                them_giao_dich_panelMousePressed(evt);
            }
        });

        them_giao_dich_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        them_giao_dich_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        them_giao_dich_label.setText("Thêm giao dịch mới");

        javax.swing.GroupLayout them_giao_dich_panelLayout = new javax.swing.GroupLayout(them_giao_dich_panel);
        them_giao_dich_panel.setLayout(them_giao_dich_panelLayout);
        them_giao_dich_panelLayout.setHorizontalGroup(
            them_giao_dich_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(them_giao_dich_label, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        them_giao_dich_panelLayout.setVerticalGroup(
            them_giao_dich_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(them_giao_dich_label, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        show_thu_phi_panel.add(them_giao_dich_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 400, 30));

        show_panel.add(show_thu_phi_panel, "card7");

        show_khoan_phi_panel.setBackground(new java.awt.Color(255, 255, 255));
        show_khoan_phi_panel.setMinimumSize(new java.awt.Dimension(700, 600));
        show_khoan_phi_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tt_khoan_phi_panel.setBackground(new java.awt.Color(67, 85, 133));

        tt_khoan_phi_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tt_khoan_phi_label.setForeground(new java.awt.Color(255, 255, 255));
        tt_khoan_phi_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tt_khoan_phi_label.setText("THÔNG TIN ĐÓNG PHÍ");

        javax.swing.GroupLayout tt_khoan_phi_panelLayout = new javax.swing.GroupLayout(tt_khoan_phi_panel);
        tt_khoan_phi_panel.setLayout(tt_khoan_phi_panelLayout);
        tt_khoan_phi_panelLayout.setHorizontalGroup(
            tt_khoan_phi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tt_khoan_phi_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tt_khoan_phi_label, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        tt_khoan_phi_panelLayout.setVerticalGroup(
            tt_khoan_phi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tt_khoan_phi_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tt_khoan_phi_label, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        show_khoan_phi_panel.add(tt_khoan_phi_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        searching_khoan_phi_field.setText("Tìm kiếm theo tên chủ hộ");
        searching_khoan_phi_field.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searching_khoan_phi_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searching_khoan_phi_fieldMouseClicked(evt);
            }
        });
        show_khoan_phi_panel.add(searching_khoan_phi_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 213, 40));

        searching_khoan_phi_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search_Icon.png"))); // NOI18N
        searching_khoan_phi_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searching_khoan_phi_buttonActionPerformed(evt);
            }
        });
        show_khoan_phi_panel.add(searching_khoan_phi_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 40, 40));

        searching_khoan_phi_question_label.setText("Bạn muốn tìm kiếm theo:");
        show_khoan_phi_panel.add(searching_khoan_phi_question_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 134, 40));

        searching_khoan_phi_type_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên chủ hộ", "Mã nhân khẩu", "Mã hộ khẩu", " ", " " }));
        searching_khoan_phi_type_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searching_khoan_phi_type_boxActionPerformed(evt);
            }
        });
        show_khoan_phi_panel.add(searching_khoan_phi_type_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 150, 40));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable3);

        show_khoan_phi_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 560, 310));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        show_khoan_phi_panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, -1, 60));

        show_panel.add(show_khoan_phi_panel, "card6");

        menu_panel.setBackground(new java.awt.Color(54, 48, 98));

        nhan_khau_bt_panel.setBackground(new java.awt.Color(54, 48, 98));
        nhan_khau_bt_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nhan_khau_bt_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nhan_khau_bt_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nhan_khau_bt_panelMousePressed(evt);
            }
        });

        nhan_khau_bt_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nhan_khau_bt_label.setForeground(new java.awt.Color(255, 255, 255));
        nhan_khau_bt_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nhan_khau_bt_label.setText("Nhân khẩu");

        javax.swing.GroupLayout nhan_khau_bt_panelLayout = new javax.swing.GroupLayout(nhan_khau_bt_panel);
        nhan_khau_bt_panel.setLayout(nhan_khau_bt_panelLayout);
        nhan_khau_bt_panelLayout.setHorizontalGroup(
            nhan_khau_bt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nhan_khau_bt_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        nhan_khau_bt_panelLayout.setVerticalGroup(
            nhan_khau_bt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nhan_khau_bt_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        ho_khau_bt_panel.setBackground(new java.awt.Color(54, 48, 98));
        ho_khau_bt_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ho_khau_bt_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ho_khau_bt_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ho_khau_bt_panelMousePressed(evt);
            }
        });

        ho_khau_bt_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ho_khau_bt_label.setForeground(new java.awt.Color(255, 255, 255));
        ho_khau_bt_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ho_khau_bt_label.setText("Hộ khẩu");

        javax.swing.GroupLayout ho_khau_bt_panelLayout = new javax.swing.GroupLayout(ho_khau_bt_panel);
        ho_khau_bt_panel.setLayout(ho_khau_bt_panelLayout);
        ho_khau_bt_panelLayout.setHorizontalGroup(
            ho_khau_bt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ho_khau_bt_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ho_khau_bt_panelLayout.setVerticalGroup(
            ho_khau_bt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ho_khau_bt_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        ho_so_bt_panel.setBackground(new java.awt.Color(54, 48, 98));
        ho_so_bt_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ho_so_bt_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ho_so_bt_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ho_so_bt_panelMousePressed(evt);
            }
        });

        ho_so_bt_label.setBackground(new java.awt.Color(0, 255, 255));
        ho_so_bt_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ho_so_bt_label.setForeground(new java.awt.Color(255, 255, 255));
        ho_so_bt_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ho_so_bt_label.setText("Hồ sơ");

        javax.swing.GroupLayout ho_so_bt_panelLayout = new javax.swing.GroupLayout(ho_so_bt_panel);
        ho_so_bt_panel.setLayout(ho_so_bt_panelLayout);
        ho_so_bt_panelLayout.setHorizontalGroup(
            ho_so_bt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ho_so_bt_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ho_so_bt_panelLayout.setVerticalGroup(
            ho_so_bt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ho_so_bt_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        home_bt_panel.setBackground(new java.awt.Color(54, 48, 98));
        home_bt_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_bt_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home_bt_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                home_bt_panelMousePressed(evt);
            }
        });

        home_bt_label.setBackground(new java.awt.Color(0, 255, 255));
        home_bt_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        home_bt_label.setForeground(new java.awt.Color(255, 255, 255));
        home_bt_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_bt_label.setText("Trang chủ");

        javax.swing.GroupLayout home_bt_panelLayout = new javax.swing.GroupLayout(home_bt_panel);
        home_bt_panel.setLayout(home_bt_panelLayout);
        home_bt_panelLayout.setHorizontalGroup(
            home_bt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_bt_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        home_bt_panelLayout.setVerticalGroup(
            home_bt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_bt_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        khoan_phi_bt_panel.setBackground(new java.awt.Color(54, 48, 98));
        khoan_phi_bt_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                khoan_phi_bt_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                khoan_phi_bt_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                khoan_phi_bt_panelMousePressed(evt);
            }
        });

        khoan_phi_bt_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        khoan_phi_bt_label.setForeground(new java.awt.Color(255, 255, 255));
        khoan_phi_bt_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        khoan_phi_bt_label.setText("Khoản phí");

        javax.swing.GroupLayout khoan_phi_bt_panelLayout = new javax.swing.GroupLayout(khoan_phi_bt_panel);
        khoan_phi_bt_panel.setLayout(khoan_phi_bt_panelLayout);
        khoan_phi_bt_panelLayout.setHorizontalGroup(
            khoan_phi_bt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(khoan_phi_bt_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        khoan_phi_bt_panelLayout.setVerticalGroup(
            khoan_phi_bt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(khoan_phi_bt_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        dang_xuat_bt_panel.setBackground(new java.awt.Color(54, 48, 98));
        dang_xuat_bt_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dang_xuat_bt_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dang_xuat_bt_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dang_xuat_bt_panelMousePressed(evt);
            }
        });

        dang_xuat_bt_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dang_xuat_bt_label.setForeground(new java.awt.Color(255, 255, 255));
        dang_xuat_bt_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dang_xuat_bt_label.setText("ĐĂNG XUẤT");

        javax.swing.GroupLayout dang_xuat_bt_panelLayout = new javax.swing.GroupLayout(dang_xuat_bt_panel);
        dang_xuat_bt_panel.setLayout(dang_xuat_bt_panelLayout);
        dang_xuat_bt_panelLayout.setHorizontalGroup(
            dang_xuat_bt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dang_xuat_bt_label, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );
        dang_xuat_bt_panelLayout.setVerticalGroup(
            dang_xuat_bt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dang_xuat_bt_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        thu_phi_bt_panel.setBackground(new java.awt.Color(54, 48, 98));
        thu_phi_bt_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                thu_phi_bt_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                thu_phi_bt_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                thu_phi_bt_panelMousePressed(evt);
            }
        });

        thu_phi_bt_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        thu_phi_bt_label.setForeground(new java.awt.Color(255, 255, 255));
        thu_phi_bt_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thu_phi_bt_label.setText("Thu phí");

        javax.swing.GroupLayout thu_phi_bt_panelLayout = new javax.swing.GroupLayout(thu_phi_bt_panel);
        thu_phi_bt_panel.setLayout(thu_phi_bt_panelLayout);
        thu_phi_bt_panelLayout.setHorizontalGroup(
            thu_phi_bt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(thu_phi_bt_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        thu_phi_bt_panelLayout.setVerticalGroup(
            thu_phi_bt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(thu_phi_bt_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menu_panelLayout = new javax.swing.GroupLayout(menu_panel);
        menu_panel.setLayout(menu_panelLayout);
        menu_panelLayout.setHorizontalGroup(
            menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nhan_khau_bt_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ho_khau_bt_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ho_so_bt_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(home_bt_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(khoan_phi_bt_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dang_xuat_bt_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(thu_phi_bt_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menu_panelLayout.setVerticalGroup(
            menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_panelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(home_bt_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nhan_khau_bt_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ho_khau_bt_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ho_so_bt_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(khoan_phi_bt_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thu_phi_bt_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(dang_xuat_bt_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(show_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(show_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nhan_khau_bt_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhan_khau_bt_panelMousePressed
        // TODO add your handling code here:
        khoan_phi_bt_panel.setBackground(new Color(54,48,98));
        home_bt_panel.setBackground(new Color(54,48,98));
        ho_so_bt_panel.setBackground(new Color(54,48,98));
        ho_khau_bt_panel.setBackground(new Color(54,48,98));
        thu_phi_bt_panel.setBackground(new Color(54,48,98));
        nhan_khau_bt_panel.setBackground(new Color(129,143,180));
        show_khoan_phi_panel.setVisible(false);
        show_home_panel.setVisible(false);
        show_ho_khau_panel.setVisible(false);
        show_ho_so_panel.setVisible(false);
        show_thu_phi_panel.setVisible(false);
        show_nhan_khau_panel.setVisible(true);
        
    }//GEN-LAST:event_nhan_khau_bt_panelMousePressed

    private void ho_khau_bt_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ho_khau_bt_panelMousePressed
        // TODO add your handling code here:
        khoan_phi_bt_panel.setBackground(new Color(54,48,98));
        home_bt_panel.setBackground(new Color(54,48,98));
        ho_so_bt_panel.setBackground(new Color(54,48,98));
        nhan_khau_bt_panel.setBackground(new Color(54,48,98));
        thu_phi_bt_panel.setBackground(new Color(54,48,98));
        ho_khau_bt_panel.setBackground(new Color(129,143,180));
        show_khoan_phi_panel.setVisible(false);
        show_home_panel.setVisible(false);
        show_nhan_khau_panel.setVisible(false);
        show_ho_so_panel.setVisible(false);
        show_thu_phi_panel.setVisible(false);
        show_ho_khau_panel.setVisible(true);
    }//GEN-LAST:event_ho_khau_bt_panelMousePressed

    private void ho_so_bt_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ho_so_bt_panelMousePressed
        // TODO add your handling code here:
        khoan_phi_bt_panel.setBackground(new Color(54,48,98));
        home_bt_panel.setBackground(new Color(54,48,98));
        nhan_khau_bt_panel.setBackground(new Color(54,48,98));
        ho_khau_bt_panel.setBackground(new Color(54,48,98));
        thu_phi_bt_panel.setBackground(new Color(54,48,98));
        ho_so_bt_panel.setBackground(new Color(129,143,180));
        show_khoan_phi_panel.setVisible(false);
        show_home_panel.setVisible(false);
        show_nhan_khau_panel.setVisible(false);
        show_ho_khau_panel.setVisible(false);
        show_thu_phi_panel.setVisible(false);
        show_ho_so_panel.setVisible(true);
    }//GEN-LAST:event_ho_so_bt_panelMousePressed

    private void home_bt_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_bt_panelMousePressed
        // TODO add your handling code here:
        khoan_phi_bt_panel.setBackground(new Color(54,48,98));
        nhan_khau_bt_panel.setBackground(new Color(54,48,98));
        ho_khau_bt_panel.setBackground(new Color(54,48,98));
        ho_so_bt_panel.setBackground(new Color(54,48,98));
        thu_phi_bt_panel.setBackground(new Color(54,48,98));
        home_bt_panel.setBackground(new Color(129,143,180));
        show_khoan_phi_panel.setVisible(false);
        show_nhan_khau_panel.setVisible(false);
        show_ho_khau_panel.setVisible(false);
        show_ho_so_panel.setVisible(false);
        show_thu_phi_panel.setVisible(false);
        show_home_panel.setVisible(true);
    }//GEN-LAST:event_home_bt_panelMousePressed

    private void searching_ho_khau_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searching_ho_khau_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searching_ho_khau_buttonActionPerformed

    private void searching_ho_khau_type_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searching_ho_khau_type_boxActionPerformed
        // TODO add your handling code here:
        String searching_type = String.valueOf(searching_ho_khau_type_box.getSelectedItem());
        if(searching_type == "Mã hộ khẩu") {
            searching_ho_khau_field.setText("Tìm kiếm theo mã hộ khẩu");
        }
        else if(searching_type == "Số nhân khẩu") {
            searching_ho_khau_field.setText("Tìm kiếm theo số lượng nhân khẩu");
        }
    }//GEN-LAST:event_searching_ho_khau_type_boxActionPerformed

    private void them_tt_ho_khau_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_them_tt_ho_khau_panelMouseEntered
        // TODO add your handling code here:
        them_tt_ho_khau_panel.setBackground(new Color(245,232,199));
    }//GEN-LAST:event_them_tt_ho_khau_panelMouseEntered

    private void them_tt_ho_khau_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_them_tt_ho_khau_panelMouseExited
        // TODO add your handling code here:
        them_tt_ho_khau_panel.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_them_tt_ho_khau_panelMouseExited

    private void sua_tt_ho_khau_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sua_tt_ho_khau_panelMouseEntered
        // TODO add your handling code here:
        sua_tt_ho_khau_panel.setBackground(new Color(245,232,199));
    }//GEN-LAST:event_sua_tt_ho_khau_panelMouseEntered

    private void sua_tt_ho_khau_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sua_tt_ho_khau_panelMouseExited
        // TODO add your handling code here:
        sua_tt_ho_khau_panel.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_sua_tt_ho_khau_panelMouseExited

    private void xoa_tt_ho_khau_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoa_tt_ho_khau_panelMouseEntered
        // TODO add your handling code here:
        xoa_tt_ho_khau_panel.setBackground(new Color(245,232,199));
    }//GEN-LAST:event_xoa_tt_ho_khau_panelMouseEntered

    private void xoa_tt_ho_khau_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoa_tt_ho_khau_panelMouseExited
        // TODO add your handling code here:
        xoa_tt_ho_khau_panel.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_xoa_tt_ho_khau_panelMouseExited

    private void searching_nhan_khau_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searching_nhan_khau_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searching_nhan_khau_buttonActionPerformed

    private void searching_nhan_khau_type_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searching_nhan_khau_type_boxActionPerformed
        // TODO add your handling code here:
        String searching_type = String.valueOf(searching_nhan_khau_type_box.getSelectedItem());
        if(searching_type == "Họ và tên") {
            searching_nhan_khau_field.setText("Tìm kiếm theo họ và tên");
        }
        else if(searching_type == "Số điện thoại") {
            searching_nhan_khau_field.setText("Tìm kiếm theo số điện thoại");
        }
        else if(searching_type == "Mã hộ khẩu") {
            searching_nhan_khau_field.setText("Tìm kiếm theo mã hộ khẩu");
        }
        else if(searching_type == "CCCD") {
            searching_nhan_khau_field.setText("Tìm kiếm theo CCCD");
        }
    }//GEN-LAST:event_searching_nhan_khau_type_boxActionPerformed

    private void sua_tt_nhan_khau_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sua_tt_nhan_khau_panelMouseEntered
        // TODO add your handling code here:
        sua_tt_nhan_khau_panel.setBackground(new Color(245,232,199));
    }//GEN-LAST:event_sua_tt_nhan_khau_panelMouseEntered

    private void sua_tt_nhan_khau_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sua_tt_nhan_khau_panelMouseExited
        // TODO add your handling code here:
        sua_tt_nhan_khau_panel.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_sua_tt_nhan_khau_panelMouseExited

    private void them_tt_nhan_khau_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_them_tt_nhan_khau_panelMouseEntered
        // TODO add your handling code here:
        them_tt_nhan_khau_panel.setBackground(new Color(245,232,199));
    }//GEN-LAST:event_them_tt_nhan_khau_panelMouseEntered

    private void them_tt_nhan_khau_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_them_tt_nhan_khau_panelMouseExited
        // TODO add your handling code here:
        them_tt_nhan_khau_panel.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_them_tt_nhan_khau_panelMouseExited

    private void xoa_tt_nhan_khau_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoa_tt_nhan_khau_panelMouseEntered
        // TODO add your handling code here:
        xoa_tt_nhan_khau_panel.setBackground(new Color(245,232,199));
    }//GEN-LAST:event_xoa_tt_nhan_khau_panelMouseEntered

    private void xoa_tt_nhan_khau_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoa_tt_nhan_khau_panelMouseExited
        // TODO add your handling code here:
        xoa_tt_nhan_khau_panel.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_xoa_tt_nhan_khau_panelMouseExited

    private void searching_ho_khau_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searching_ho_khau_fieldMouseClicked
        // TODO add your handling code here:
        searching_ho_khau_field.setText("");
    }//GEN-LAST:event_searching_ho_khau_fieldMouseClicked

    private void searching_nhan_khau_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searching_nhan_khau_fieldMouseClicked
        // TODO add your handling code here:
        searching_nhan_khau_field.setText("");
    }//GEN-LAST:event_searching_nhan_khau_fieldMouseClicked

    private void searching_khoan_phi_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searching_khoan_phi_fieldMouseClicked
        // TODO add your handling code here:
        searching_khoan_phi_field.setText("");
    }//GEN-LAST:event_searching_khoan_phi_fieldMouseClicked

    private void searching_khoan_phi_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searching_khoan_phi_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searching_khoan_phi_buttonActionPerformed

    private void searching_khoan_phi_type_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searching_khoan_phi_type_boxActionPerformed
        // TODO add your handling code here:
        String searching_type = String.valueOf(searching_khoan_phi_type_box.getSelectedItem());
        if(searching_type == "Tên chủ hộ") {
            searching_khoan_phi_field.setText("Tìm kiếm theo tên chủ hộ");
        }
        else if(searching_type == "Mã nhân khẩu") {
            searching_khoan_phi_field.setText("Tìm kiếm theo mã nhân khẩu");
        }
        else if(searching_type == "Mã hộ khẩu") {
            searching_khoan_phi_field.setText("Tìm kiếm theo mã hộ khẩu");
        }
    }//GEN-LAST:event_searching_khoan_phi_type_boxActionPerformed

    private void khoan_phi_bt_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khoan_phi_bt_panelMousePressed
        // TODO add your handling code here:
        home_bt_panel.setBackground(new Color(54,48,98));
        nhan_khau_bt_panel.setBackground(new Color(54,48,98));
        ho_khau_bt_panel.setBackground(new Color(54,48,98));
        ho_so_bt_panel.setBackground(new Color(54,48,98));
        thu_phi_bt_panel.setBackground(new Color(54,48,98));
        khoan_phi_bt_panel.setBackground(new Color(129,143,180));
        show_home_panel.setVisible(false);
        show_nhan_khau_panel.setVisible(false);
        show_ho_khau_panel.setVisible(false);
        show_ho_so_panel.setVisible(false);
        show_thu_phi_panel.setVisible(false);
        show_khoan_phi_panel.setVisible(true);
    }//GEN-LAST:event_khoan_phi_bt_panelMousePressed

    private void dang_xuat_bt_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dang_xuat_bt_panelMousePressed
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn đăng xuất không?", "Đăng xuất khỏi hệ thống", JOptionPane.YES_NO_OPTION);
        if(ans == 0)
        {
            LoginScreen.ShowLogin();
            this.dispose();
        }
    }//GEN-LAST:event_dang_xuat_bt_panelMousePressed

    private void dang_xuat_bt_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dang_xuat_bt_panelMouseEntered
        // TODO add your handling code here:
        dang_xuat_bt_panel.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_dang_xuat_bt_panelMouseEntered

    private void dang_xuat_bt_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dang_xuat_bt_panelMouseExited
        // TODO add your handling code here:
        dang_xuat_bt_panel.setBackground(new Color(54,48,98));
    }//GEN-LAST:event_dang_xuat_bt_panelMouseExited

    private void thu_phi_bt_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thu_phi_bt_panelMousePressed
        // TODO add your handling code here:
        khoan_phi_bt_panel.setBackground(new Color(54,48,98));
        home_bt_panel.setBackground(new Color(54,48,98));
        ho_so_bt_panel.setBackground(new Color(54,48,98));
        nhan_khau_bt_panel.setBackground(new Color(54,48,98));
        ho_khau_bt_panel.setBackground(new Color(54,48,98));
        thu_phi_bt_panel.setBackground(new Color(129, 143, 180));
        show_khoan_phi_panel.setVisible(false);
        show_home_panel.setVisible(false);
        show_nhan_khau_panel.setVisible(false);
        show_ho_so_panel.setVisible(false);
        show_ho_khau_panel.setVisible(false);
        show_thu_phi_panel.setVisible(true);
    }//GEN-LAST:event_thu_phi_bt_panelMousePressed

    private void home_bt_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_bt_panelMouseEntered
        // TODO add your handling code here:
        home_bt_panel.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_home_bt_panelMouseEntered

    private void home_bt_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_bt_panelMouseExited
        // TODO add your handling code here:
        home_bt_panel.setBackground(new Color(54,48,98));
    }//GEN-LAST:event_home_bt_panelMouseExited

    private void nhan_khau_bt_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhan_khau_bt_panelMouseEntered
        // TODO add your handling code here:
        nhan_khau_bt_panel.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_nhan_khau_bt_panelMouseEntered

    private void nhan_khau_bt_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhan_khau_bt_panelMouseExited
        // TODO add your handling code here:
        nhan_khau_bt_panel.setBackground(new Color(54,48,98));
    }//GEN-LAST:event_nhan_khau_bt_panelMouseExited

    private void ho_khau_bt_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ho_khau_bt_panelMouseEntered
        // TODO add your handling code here:
        ho_khau_bt_panel.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_ho_khau_bt_panelMouseEntered

    private void ho_khau_bt_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ho_khau_bt_panelMouseExited
        // TODO add your handling code here:
        ho_khau_bt_panel.setBackground(new Color(54,48,98));
    }//GEN-LAST:event_ho_khau_bt_panelMouseExited

    private void ho_so_bt_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ho_so_bt_panelMouseEntered
        // TODO add your handling code here:
        ho_so_bt_panel.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_ho_so_bt_panelMouseEntered

    private void ho_so_bt_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ho_so_bt_panelMouseExited
        // TODO add your handling code here:
        ho_so_bt_panel.setBackground(new Color(54,48,98));
    }//GEN-LAST:event_ho_so_bt_panelMouseExited

    private void khoan_phi_bt_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khoan_phi_bt_panelMouseEntered
        // TODO add your handling code here:
        khoan_phi_bt_panel.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_khoan_phi_bt_panelMouseEntered

    private void khoan_phi_bt_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khoan_phi_bt_panelMouseExited
        // TODO add your handling code here:
        khoan_phi_bt_panel.setBackground(new Color(54,48,98));
    }//GEN-LAST:event_khoan_phi_bt_panelMouseExited

    private void thu_phi_bt_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thu_phi_bt_panelMouseEntered
        // TODO add your handling code here:
        thu_phi_bt_panel.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_thu_phi_bt_panelMouseEntered

    private void thu_phi_bt_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thu_phi_bt_panelMouseExited
        // TODO add your handling code here:
        thu_phi_bt_panel.setBackground(new Color(54,48,98));
    }//GEN-LAST:event_thu_phi_bt_panelMouseExited

    private void searching_thu_phi_type_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searching_thu_phi_type_boxActionPerformed
        // TODO add your handling code here:
        String searching_type = String.valueOf(searching_thu_phi_type_box.getSelectedItem());
        if(searching_type == "Tên chủ hộ") {
            searching_thu_phi_field.setText("Tìm kiếm theo tên chủ hộ");
        }
        else if(searching_type == "Mã nhân khẩu") {
            searching_thu_phi_field.setText("Tìm kiếm theo mã nhân khẩu");
        }
        else if(searching_type == "Mã hộ khẩu") {
            searching_thu_phi_field.setText("Tìm kiếm theo mã hộ khẩu");
        }
        else if(searching_type == "Mã phí") {
            searching_thu_phi_field.setText("Tìm kiếm theo mã phí");
        }
        else if(searching_type == "Tên phí") {
            searching_thu_phi_field.setText("Tìm kiếm theo tên phí");
        }
    }//GEN-LAST:event_searching_thu_phi_type_boxActionPerformed

    private void searching_thu_phi_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searching_thu_phi_fieldMouseClicked
        // TODO add your handling code here:
        searching_thu_phi_field.setText("");
    }//GEN-LAST:event_searching_thu_phi_fieldMouseClicked

    private void searching_thu_phi_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searching_thu_phi_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searching_thu_phi_buttonActionPerformed

    private void them_giao_dich_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_them_giao_dich_panelMouseEntered
        // TODO add your handling code here:
        them_giao_dich_panel.setBackground(new Color(245,232,199));
    }//GEN-LAST:event_them_giao_dich_panelMouseEntered

    private void them_giao_dich_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_them_giao_dich_panelMouseExited
        // TODO add your handling code here:
        them_giao_dich_panel.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_them_giao_dich_panelMouseExited

    private void them_giao_dich_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_them_giao_dich_panelMousePressed
        // TODO add your handling code here:
        AddFeeScreen addFeeScreen = new AddFeeScreen();
        addFeeScreen.setVisible(true);
    }//GEN-LAST:event_them_giao_dich_panelMousePressed

    private void sua_tt_ho_khau_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sua_tt_ho_khau_panelMousePressed
        // TODO add your handling code here:
        int selectedRow = ho_khau_table.getSelectedRow();
        if(selectedRow != -1)
        {
            
            EditHoKhauScreen editHoKhauScreen = new EditHoKhauScreen(this);
           
            editHoKhauScreen.setVisible(true);
        }
        else JOptionPane.showMessageDialog(null, "Chọn một dòng để sửa");
    }//GEN-LAST:event_sua_tt_ho_khau_panelMousePressed

    private void sua_tt_nhan_khau_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sua_tt_nhan_khau_panelMousePressed
        // TODO add your handling code here:
        int selectedRow = nhan_khau_table.getSelectedRow();
        if(selectedRow != -1)
        {
            EditNhanKhauScreen editNhanKhauScreen = new EditNhanKhauScreen();
            editNhanKhauScreen.setParentContext(this);
            editNhanKhauScreen.setVisible(true);
        }
        else JOptionPane.showMessageDialog(null, "Chọn một dòng để sửa");
    }//GEN-LAST:event_sua_tt_nhan_khau_panelMousePressed

    private void searching_tai_khoan_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searching_tai_khoan_fieldMouseClicked
        // TODO add your handling code here:
        searching_tai_khoan_field.setText("");
    }//GEN-LAST:event_searching_tai_khoan_fieldMouseClicked

    private void searching_tai_khoan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searching_tai_khoan_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searching_tai_khoan_buttonActionPerformed

    private void searching_tai_khoan_type_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searching_tai_khoan_type_boxActionPerformed
        // TODO add your handling code here:
        String searching_type = String.valueOf(searching_tai_khoan_type_box.getSelectedItem());
        if(searching_type == "Họ và tên") {
            searching_tai_khoan_field.setText("Tìm kiếm theo họ và tên");
        }
        else if(searching_type == "Tài khoản") {
            searching_tai_khoan_field.setText("Tìm kiếm theo tài khoản");
        }
        else if(searching_type == "Mật khẩu") {
            searching_tai_khoan_field.setText("Tìm kiếm theo mật khẩu");
        }
    }//GEN-LAST:event_searching_tai_khoan_type_boxActionPerformed

    private void xoa_tt_ho_khau_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoa_tt_ho_khau_panelMousePressed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) ho_khau_table.getModel();
        int selectedRow = ho_khau_table.getSelectedRow();
        if(selectedRow != -1) tblModel.removeRow(selectedRow);
        else JOptionPane.showMessageDialog(null, "Chọn một dòng để xóa");
    }//GEN-LAST:event_xoa_tt_ho_khau_panelMousePressed

    private void xoa_tt_nhan_khau_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoa_tt_nhan_khau_panelMousePressed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) nhan_khau_table.getModel();
        int selectedRow = nhan_khau_table.getSelectedRow();
        if(selectedRow != -1) tblModel.removeRow(selectedRow);
        else JOptionPane.showMessageDialog(null, "Chọn một dòng để xóa");
    }//GEN-LAST:event_xoa_tt_nhan_khau_panelMousePressed

    private void xoa_tai_khoan_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoa_tai_khoan_panelMouseEntered
        // TODO add your handling code here:
        xoa_tai_khoan_panel.setBackground(new Color(245,232,199));
    }//GEN-LAST:event_xoa_tai_khoan_panelMouseEntered

    private void xoa_tai_khoan_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoa_tai_khoan_panelMouseExited
        // TODO add your handling code here:
        xoa_tai_khoan_panel.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_xoa_tai_khoan_panelMouseExited

    private void them_tai_khoan_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_them_tai_khoan_panelMouseEntered
        // TODO add your handling code here:
        them_tai_khoan_panel.setBackground(new Color(245,232,199));
    }//GEN-LAST:event_them_tai_khoan_panelMouseEntered

    private void them_tai_khoan_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_them_tai_khoan_panelMouseExited
        // TODO add your handling code here:
        them_tai_khoan_panel.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_them_tai_khoan_panelMouseExited

    private void xoa_tai_khoan_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoa_tai_khoan_panelMousePressed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) tai_khoan_table.getModel();
        int selectedRow = tai_khoan_table.getSelectedRow();
        if(selectedRow != -1) tblModel.removeRow(selectedRow);
        else JOptionPane.showMessageDialog(null, "Chọn một dòng để xóa");
    }//GEN-LAST:event_xoa_tai_khoan_panelMousePressed

    public JTable getHo_khau_table() {
        return ho_khau_table;
    }

    public void setHo_khau_table(JTable ho_khau_table) {
        this.ho_khau_table = ho_khau_table;
    }

    public JTable getNhan_khau_table() {
        return nhan_khau_table;
    }

    public void setNhan_khau_table(JTable nhan_khau_table) {
        this.nhan_khau_table = nhan_khau_table;
    }
    
    /**
     * @param args the command line arguments
     */
    public void ShowMain() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bm_name_label;
    private javax.swing.JLabel dang_xuat_bt_label;
    private javax.swing.JPanel dang_xuat_bt_panel;
    private javax.swing.JLabel ho_khau_bt_label;
    private javax.swing.JPanel ho_khau_bt_panel;
    private javax.swing.JScrollPane ho_khau_scroll_pane;
    private javax.swing.JTable ho_khau_table;
    private javax.swing.JLabel ho_so_bt_label;
    private javax.swing.JPanel ho_so_bt_panel;
    private javax.swing.JLabel home_bt_label;
    private javax.swing.JPanel home_bt_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel khoan_phi_bt_label;
    private javax.swing.JPanel khoan_phi_bt_panel;
    private javax.swing.JPanel menu_panel;
    private javax.swing.JLabel nhan_khau_bt_label;
    private javax.swing.JPanel nhan_khau_bt_panel;
    private javax.swing.JTable nhan_khau_table;
    private javax.swing.JLabel ql_tk_label;
    private javax.swing.JPanel ql_tk_panel;
    private javax.swing.JButton searching_ho_khau_button;
    private javax.swing.JTextField searching_ho_khau_field;
    private javax.swing.JLabel searching_ho_khau_question_label;
    private javax.swing.JComboBox<String> searching_ho_khau_type_box;
    private javax.swing.JButton searching_khoan_phi_button;
    private javax.swing.JTextField searching_khoan_phi_field;
    private javax.swing.JLabel searching_khoan_phi_question_label;
    private javax.swing.JComboBox<String> searching_khoan_phi_type_box;
    private javax.swing.JButton searching_nhan_khau_button;
    private javax.swing.JTextField searching_nhan_khau_field;
    private javax.swing.JLabel searching_nhan_khau_question_label;
    private javax.swing.JComboBox<String> searching_nhan_khau_type_box;
    private javax.swing.JButton searching_tai_khoan_button;
    private javax.swing.JTextField searching_tai_khoan_field;
    private javax.swing.JLabel searching_tai_khoan_question_label;
    private javax.swing.JComboBox<String> searching_tai_khoan_type_box;
    private javax.swing.JButton searching_thu_phi_button;
    private javax.swing.JTextField searching_thu_phi_field;
    private javax.swing.JLabel searching_thu_phi_question_label;
    private javax.swing.JComboBox<String> searching_thu_phi_type_box;
    private javax.swing.JPanel show_ho_khau_panel;
    private javax.swing.JPanel show_ho_so_panel;
    private javax.swing.JPanel show_home_panel;
    private javax.swing.JPanel show_khoan_phi_panel;
    private javax.swing.JPanel show_nhan_khau_panel;
    private javax.swing.JPanel show_panel;
    private javax.swing.JPanel show_thu_phi_panel;
    private javax.swing.JLabel sua_tt_ho_khau_label;
    private javax.swing.JPanel sua_tt_ho_khau_panel;
    private javax.swing.JLabel sua_tt_nhan_khau_label;
    private javax.swing.JPanel sua_tt_nhan_khau_panel;
    private javax.swing.JTable tai_khoan_table;
    private javax.swing.JLabel them_giao_dich_label;
    private javax.swing.JPanel them_giao_dich_panel;
    private javax.swing.JLabel them_tai_khoan_label;
    private javax.swing.JPanel them_tai_khoan_panel;
    private javax.swing.JLabel them_tt_ho_khau_label;
    private javax.swing.JPanel them_tt_ho_khau_panel;
    private javax.swing.JLabel them_tt_nhan_khau_label;
    private javax.swing.JPanel them_tt_nhan_khau_panel;
    private javax.swing.JLabel thu_phi_bt_label;
    private javax.swing.JPanel thu_phi_bt_panel;
    private javax.swing.JLabel tt_giao_dich_label;
    private javax.swing.JPanel tt_giao_dich_panel;
    private javax.swing.JLabel tt_ho_khau_label;
    private javax.swing.JPanel tt_ho_khau_panel;
    private javax.swing.JLabel tt_khoan_phi_label;
    private javax.swing.JPanel tt_khoan_phi_panel;
    private javax.swing.JLabel tt_nhan_khau_label;
    private javax.swing.JPanel tt_nhan_khau_panel;
    private javax.swing.JLabel xoa_tai_khoan_label;
    private javax.swing.JPanel xoa_tai_khoan_panel;
    private javax.swing.JLabel xoa_tt_ho_khau_label;
    private javax.swing.JPanel xoa_tt_ho_khau_panel;
    private javax.swing.JLabel xoa_tt_nhan_khau_label;
    private javax.swing.JPanel xoa_tt_nhan_khau_panel;
    // End of variables declaration//GEN-END:variables

}
