/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hust.soict.cnpm.group24.view;

import java.awt.Color;

/**
 *
 * @author ADMIN
 */
public class SignupScreen extends javax.swing.JFrame {

    /**
     * Creates new form SignupScreen
     */
    public SignupScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo_panel = new javax.swing.JPanel();
        logo_label = new javax.swing.JLabel();
        manipulating_panel = new javax.swing.JPanel();
        tieu_de_label = new javax.swing.JLabel();
        hvt_label = new javax.swing.JLabel();
        mcb_label = new javax.swing.JLabel();
        mk_label = new javax.swing.JLabel();
        nlmk_label = new javax.swing.JLabel();
        hvt_field = new javax.swing.JTextField();
        mcb_field = new javax.swing.JTextField();
        mk_field = new javax.swing.JPasswordField();
        nlmk_field = new javax.swing.JPasswordField();
        enter_signup_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blue Manager - Đăng ký");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(400, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_panel.setBackground(new java.awt.Color(67, 85, 133));

        logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hust/soict/cnpm/group24/icon/Blue Manager-logos_white.png"))); // NOI18N

        javax.swing.GroupLayout logo_panelLayout = new javax.swing.GroupLayout(logo_panel);
        logo_panel.setLayout(logo_panelLayout);
        logo_panelLayout.setHorizontalGroup(
            logo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo_panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(logo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        logo_panelLayout.setVerticalGroup(
            logo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo_panelLayout.createSequentialGroup()
                .addComponent(logo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(logo_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        manipulating_panel.setBackground(new java.awt.Color(255, 255, 255));
        manipulating_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tieu_de_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tieu_de_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tieu_de_label.setText("ĐĂNG KÝ TÀI KHOẢN");
        manipulating_panel.add(tieu_de_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 25, 221, 38));

        hvt_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hvt_label.setText("Họ và tên:");
        manipulating_panel.add(hvt_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 81, 123, 40));

        mcb_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mcb_label.setText("Mã cán bộ:");
        manipulating_panel.add(mcb_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 128, 123, 40));

        mk_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mk_label.setText("Mật khẩu:");
        manipulating_panel.add(mk_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 123, 40));

        nlmk_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nlmk_label.setText("Nhập lại mật khẩu:");
        manipulating_panel.add(nlmk_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 123, 40));

        hvt_field.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manipulating_panel.add(hvt_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 154, 40));

        mcb_field.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manipulating_panel.add(mcb_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 154, 40));

        mk_field.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manipulating_panel.add(mk_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 154, 40));

        nlmk_field.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manipulating_panel.add(nlmk_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 154, 40));

        enter_signup_button.setBackground(new java.awt.Color(129, 143, 180));
        enter_signup_button.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        enter_signup_button.setText("Đăng ký");
        enter_signup_button.setFocusable(false);
        enter_signup_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enter_signup_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enter_signup_buttonMouseExited(evt);
            }
        });
        enter_signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_signup_buttonActionPerformed(evt);
            }
        });
        manipulating_panel.add(enter_signup_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 320, 181, 50));

        getContentPane().add(manipulating_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 400, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enter_signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_signup_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enter_signup_buttonActionPerformed

    private void enter_signup_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter_signup_buttonMouseEntered
        // TODO add your handling code here:
        enter_signup_button.setBackground(new Color(245,232,199));
    }//GEN-LAST:event_enter_signup_buttonMouseEntered

    private void enter_signup_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter_signup_buttonMouseExited
        // TODO add your handling code here:
        enter_signup_button.setBackground(new Color(129,143,180));
    }//GEN-LAST:event_enter_signup_buttonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void showSignup() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enter_signup_button;
    private javax.swing.JTextField hvt_field;
    private javax.swing.JLabel hvt_label;
    private javax.swing.JLabel logo_label;
    private javax.swing.JPanel logo_panel;
    private javax.swing.JPanel manipulating_panel;
    private javax.swing.JTextField mcb_field;
    private javax.swing.JLabel mcb_label;
    private javax.swing.JPasswordField mk_field;
    private javax.swing.JLabel mk_label;
    private javax.swing.JPasswordField nlmk_field;
    private javax.swing.JLabel nlmk_label;
    private javax.swing.JLabel tieu_de_label;
    // End of variables declaration//GEN-END:variables
}
