/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hust.soict.cnpm.group24.view.nopphiview;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.hust.soict.cnpm.group24.model.dao.HoKhauDAO;
import com.hust.soict.cnpm.group24.model.entity.HoKhau;
import com.hust.soict.cnpm.group24.model.entity.KhoanPhi;
import com.hust.soict.cnpm.group24.view.hokhauview.CapNhatHoKhau;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class AddFee_SelectMaHoScreen extends javax.swing.JFrame {
    private NopPhiScreen parentContext;
    /**
     * Creates new form AddFee_SelectMaHoScreen
     */
    public AddFee_SelectMaHoScreen(NopPhiScreen pContext) {
        initComponents();
        parentContext = pContext;
        loadHoKhauTable();
        parentContext.setEnabled(false);
        setLocationRelativeTo(null);
    }

    @Override
    public void dispose() {
        super.dispose();
        parentContext.setEnabled(true);
        parentContext.setVisible(true);
    }

    public void loadHoKhauTable(){
        DefaultTableModel tableModel = (DefaultTableModel)ho_khau_table.getModel();
        int rowCount = tableModel.getRowCount();
        for (int i = rowCount; i > 0 ; i--){
            tableModel.removeRow(i-1);
        }
        List<HoKhau> hoKhauList = HoKhauDAO.getListHoKhau();
        for(HoKhau hoKhau : hoKhauList){
            tableModel.addRow(new Object[]{hoKhau.getMaHo(),hoKhau.getTenChuHo(),hoKhau.getSoThanhVien(),
                            hoKhau.getDienTich(),hoKhau.getSoXe(),hoKhau.getSoOto()});
        }
    }
    
    public void findHoKhauTable(List<HoKhau> hoKhauList){
        DefaultTableModel tableModel = (DefaultTableModel)ho_khau_table.getModel();
        int rowCount = tableModel.getRowCount();
        for (int i = rowCount; i > 0 ; i--){
            tableModel.removeRow(i-1);
        }

        for(HoKhau hoKhau : hoKhauList){
            tableModel.addRow(new Object[]{hoKhau.getMaHo(),hoKhau.getTenChuHo(),hoKhau.getSoThanhVien(),
                    hoKhau.getDienTich(),hoKhau.getSoXe(),hoKhau.getSoOto()});
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tt_ho_khau_panel = new javax.swing.JPanel();
        tt_ho_khau_label = new javax.swing.JLabel();
        confirm_button = new com.k33ptoo.components.KButton();
        ho_khau_scroll_pane = new javax.swing.JScrollPane();
        ho_khau_table = new javax.swing.JTable();
        searching_ho_khau_field = new javax.swing.JTextField();
        searching_ho_khau_button = new javax.swing.JButton();
        searching_ho_khau_question_label = new javax.swing.JLabel();
        searching_ho_khau_type_box = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 620));
        setPreferredSize(new java.awt.Dimension(700, 620));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tt_ho_khau_panel.setBackground(new java.awt.Color(67, 85, 133));

        tt_ho_khau_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tt_ho_khau_label.setForeground(new java.awt.Color(255, 255, 255));
        tt_ho_khau_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tt_ho_khau_label.setText("THÔNG TIN HỘ KHẨU");

        javax.swing.GroupLayout tt_ho_khau_panelLayout = new javax.swing.GroupLayout(tt_ho_khau_panel);
        tt_ho_khau_panel.setLayout(tt_ho_khau_panelLayout);
        tt_ho_khau_panelLayout.setHorizontalGroup(
            tt_ho_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tt_ho_khau_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tt_ho_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        tt_ho_khau_panelLayout.setVerticalGroup(
            tt_ho_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tt_ho_khau_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tt_ho_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(tt_ho_khau_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        confirm_button.setText("Xác nhận");
        confirm_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        confirm_button.setkBackGroundColor(new java.awt.Color(36, 193, 93));
        confirm_button.setkEndColor(new java.awt.Color(36, 193, 93));
        confirm_button.setkHoverEndColor(new java.awt.Color(36, 193, 93));
        confirm_button.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        confirm_button.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        confirm_button.setkPressedColor(new java.awt.Color(0, 51, 51));
        confirm_button.setkStartColor(new java.awt.Color(36, 193, 93));
        confirm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(confirm_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, -1, -1));

        ho_khau_scroll_pane.setAutoscrolls(true);

        ho_khau_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hộ", "Tên chủ hộ ", "Số thành viên", "Diện tích", "Số xe máy", "Số ô tô"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ho_khau_table.getTableHeader().setReorderingAllowed(false);
        ho_khau_scroll_pane.setViewportView(ho_khau_table);

        getContentPane().add(ho_khau_scroll_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 560, 300));

        searching_ho_khau_field.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searching_ho_khau_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searching_ho_khau_fieldMouseClicked(evt);
            }
        });
        searching_ho_khau_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searching_ho_khau_fieldKeyPressed(evt);
            }
        });
        getContentPane().add(searching_ho_khau_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 213, 40));

        searching_ho_khau_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        searching_ho_khau_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searching_ho_khau_buttonMousePressed(evt);
            }
        });
        getContentPane().add(searching_ho_khau_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 40, 40));

        searching_ho_khau_question_label.setText("Bạn muốn tìm kiếm theo:");
        getContentPane().add(searching_ho_khau_question_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 134, 40));

        searching_ho_khau_type_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã hộ khẩu", "Tên chủ hộ" }));
        getContentPane().add(searching_ho_khau_type_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirm_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_buttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)ho_khau_table.getModel();
        int selectedRow = ho_khau_table.getSelectedRow();
        if(selectedRow != -1){
            String ma_ho_khau = tblModel.getValueAt(ho_khau_table.getSelectedRow(), 0).toString();
            parentContext.getMa_ho_field().setText(ma_ho_khau);
            this.dispose();
        }
        else JOptionPane.showMessageDialog(null, "Hãy chọn một dòng!");
        
    }//GEN-LAST:event_confirm_buttonActionPerformed

    private void searching_ho_khau_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searching_ho_khau_fieldMouseClicked
        // TODO add your handling code here:
        searching_ho_khau_field.setText("");
    }//GEN-LAST:event_searching_ho_khau_fieldMouseClicked

    private void searching_ho_khau_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searching_ho_khau_fieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(searching_ho_khau_type_box.getSelectedIndex()==0){
                List<HoKhau> list = HoKhauDAO.find(searching_ho_khau_field.getText(), HoKhauDAO.MA_HO);
                findHoKhauTable(list);
            }else if(searching_ho_khau_type_box.getSelectedIndex()==1){
                List<HoKhau> list = HoKhauDAO.find(searching_ho_khau_field.getText(), HoKhauDAO.TEN_CHU_HO);
                findHoKhauTable(list);
            }
        }
    }//GEN-LAST:event_searching_ho_khau_fieldKeyPressed

    private void searching_ho_khau_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searching_ho_khau_buttonMousePressed
        // TODO add your handling code here:
        if(searching_ho_khau_type_box.getSelectedIndex()==0){
            List<HoKhau> list = HoKhauDAO.find(searching_ho_khau_field.getText(), HoKhauDAO.MA_HO);
            findHoKhauTable(list);
        }else if(searching_ho_khau_type_box.getSelectedIndex()==1){
            List<HoKhau> list = HoKhauDAO.find(searching_ho_khau_field.getText(), HoKhauDAO.TEN_CHU_HO);
            findHoKhauTable(list);
        }
    }//GEN-LAST:event_searching_ho_khau_buttonMousePressed

    public NopPhiScreen getParentContext() {
        return parentContext;
    }

    public void setParentContext(NopPhiScreen parentContext) {
        this.parentContext = parentContext;
    }


    public static void showScreen(NopPhiScreen pContext) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFee_SelectMaHoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFee_SelectMaHoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFee_SelectMaHoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFee_SelectMaHoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFee_SelectMaHoScreen(pContext).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton confirm_button;
    private javax.swing.JScrollPane ho_khau_scroll_pane;
    private javax.swing.JTable ho_khau_table;
    private javax.swing.JButton searching_ho_khau_button;
    private javax.swing.JTextField searching_ho_khau_field;
    private javax.swing.JLabel searching_ho_khau_question_label;
    private javax.swing.JComboBox<String> searching_ho_khau_type_box;
    private javax.swing.JLabel tt_ho_khau_label;
    private javax.swing.JPanel tt_ho_khau_panel;
    // End of variables declaration//GEN-END:variables
}
