/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hust.soict.cnpm.group24.view.nopphiview;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class AddFee_SelectMaHoScreen extends javax.swing.JFrame {
    private NopPhiScreen parentContext;
    /**
     * Creates new form AddFee_SelectMaHoScreen
     */
    public AddFee_SelectMaHoScreen() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searching_ho_khau_type_box = new javax.swing.JComboBox<>();
        searching_ho_khau_question_label = new javax.swing.JLabel();
        searching_ho_khau_button = new javax.swing.JButton();
        ho_khau_scroll_pane = new javax.swing.JScrollPane();
        ho_khau_table = new javax.swing.JTable();
        tt_ho_khau_panel = new javax.swing.JPanel();
        tt_ho_khau_label = new javax.swing.JLabel();
        searching_ho_khau_field = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        confirm_button = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searching_ho_khau_type_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã hộ khẩu", "Số nhân khẩu", " " }));
        searching_ho_khau_type_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searching_ho_khau_type_boxActionPerformed(evt);
            }
        });
        getContentPane().add(searching_ho_khau_type_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 150, 40));

        searching_ho_khau_question_label.setText("Bạn muốn tìm kiếm theo:");
        getContentPane().add(searching_ho_khau_question_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 134, 40));

        searching_ho_khau_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search_Icon.png"))); // NOI18N
        searching_ho_khau_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searching_ho_khau_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(searching_ho_khau_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 40, 40));

        ho_khau_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"HQT", "dmm", " ", " "},
                {"1212", "7", "333", " "}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ho_khau_scroll_pane.setViewportView(ho_khau_table);

        getContentPane().add(ho_khau_scroll_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 560, 300));

        tt_ho_khau_panel.setBackground(new java.awt.Color(67, 85, 133));

        tt_ho_khau_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tt_ho_khau_label.setForeground(new java.awt.Color(255, 255, 255));
        tt_ho_khau_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tt_ho_khau_label.setText("THÔNG TIN HỘ KHẨU");

        javax.swing.GroupLayout tt_ho_khau_panelLayout = new javax.swing.GroupLayout(tt_ho_khau_panel);
        tt_ho_khau_panel.setLayout(tt_ho_khau_panelLayout);
        tt_ho_khau_panelLayout.setHorizontalGroup(
            tt_ho_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tt_ho_khau_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tt_ho_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        tt_ho_khau_panelLayout.setVerticalGroup(
            tt_ho_khau_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tt_ho_khau_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tt_ho_khau_label, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(tt_ho_khau_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        searching_ho_khau_field.setText("Tìm kiếm theo mã hộ khẩu");
        searching_ho_khau_field.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searching_ho_khau_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searching_ho_khau_fieldMouseClicked(evt);
            }
        });
        getContentPane().add(searching_ho_khau_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 213, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, -1, 70));

        confirm_button.setText("Xác nhận");
        confirm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(confirm_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searching_ho_khau_type_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searching_ho_khau_type_boxActionPerformed
        // TODO add your handling code here:
        String searching_type = String.valueOf(searching_ho_khau_type_box.getSelectedItem());
        if(searching_type == "Mã hộ khẩu") {
            searching_ho_khau_field.setText("Tìm kiếm theo mã hộ khẩu");
        }
        else if(searching_type == "Số nhân khẩu") {
            searching_ho_khau_field.setText("Tìm kiếm theo số lượng nhân khẩu");
        }
    }//GEN-LAST:event_searching_ho_khau_type_boxActionPerformed

    private void searching_ho_khau_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searching_ho_khau_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searching_ho_khau_buttonActionPerformed

    private void searching_ho_khau_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searching_ho_khau_fieldMouseClicked
        // TODO add your handling code here:
        searching_ho_khau_field.setText("");
    }//GEN-LAST:event_searching_ho_khau_fieldMouseClicked

    private void confirm_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_buttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)ho_khau_table.getModel();
        
        String ten_chu_ho = tblModel.getValueAt(ho_khau_table.getSelectedRow(), 0).toString();
        String ma_chu_ho = tblModel.getValueAt(ho_khau_table.getSelectedRow(), 1).toString();
        String ma_ho_khau = tblModel.getValueAt(ho_khau_table.getSelectedRow(), 2).toString();
        parentContext.getMa_ho_field().setText(ten_chu_ho);
        this.dispose();
    }//GEN-LAST:event_confirm_buttonActionPerformed

    public NopPhiScreen getParentContext() {
        return parentContext;
    }

    public void setParentContext(NopPhiScreen parentContext) {
        this.parentContext = parentContext;
    }

    /**
     * @param args the command line arguments
     */
    public void showScreen() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFee_SelectMaHoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFee_SelectMaHoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFee_SelectMaHoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFee_SelectMaHoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFee_SelectMaHoScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton confirm_button;
    private javax.swing.JScrollPane ho_khau_scroll_pane;
    private javax.swing.JTable ho_khau_table;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searching_ho_khau_button;
    private javax.swing.JTextField searching_ho_khau_field;
    private javax.swing.JLabel searching_ho_khau_question_label;
    private javax.swing.JComboBox<String> searching_ho_khau_type_box;
    private javax.swing.JLabel tt_ho_khau_label;
    private javax.swing.JPanel tt_ho_khau_panel;
    // End of variables declaration//GEN-END:variables
}
