/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hust.soict.cnpm.group24.view.nopphiview;

import com.formdev.flatlaf.FlatLightLaf;
import com.hust.soict.cnpm.group24.controller.NopPhiController;
import com.hust.soict.cnpm.group24.model.dao.NopPhiDAO;
import com.hust.soict.cnpm.group24.model.entity.NopPhi;
import com.hust.soict.cnpm.group24.view.MainScreen;

import javax.swing.*;
import java.sql.Date;
import java.text.DecimalFormat;

/**
 *
 * @author ADMIN
 */
public class NopPhiScreen extends javax.swing.JFrame {

    private MainScreen parentContext;
    /**
     * Creates new form AddFeeScreen
     */
    public NopPhiScreen(MainScreen pContext) {
        initComponents();
        parentContext = pContext;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        tieu_de_label = new javax.swing.JLabel();
        ma_ho_label = new javax.swing.JLabel();
        ma_phi_label = new javax.swing.JLabel();
        ten_phi_label = new javax.swing.JLabel();
        ngay_nop_label = new javax.swing.JLabel();
        ma_ho_field = new javax.swing.JTextField();
        so_tien_field = new javax.swing.JTextField();
        so_tien_label = new javax.swing.JLabel();
        ten_phi_field = new javax.swing.JTextField();
        ma_phi_select_button = new javax.swing.JButton();
        ma_ho_select_button = new javax.swing.JButton();
        ma_phi_field = new javax.swing.JTextField();
        ngayNopDateChooser = new com.toedter.calendar.JDateChooser();
        money_calc_button = new javax.swing.JButton();
        themButton = new com.k33ptoo.components.KButton();
        huyButton = new com.k33ptoo.components.KButton();
        ten_nguoi_dong_label = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ten_nguoi_dong_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm giao dịch");

        kGradientPanel1.setOpaque(false);
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(900, 750));

        kGradientPanel2.setkBorderRadius(70);
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setOpaque(false);
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(788, 534));

        tieu_de_label.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        tieu_de_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tieu_de_label.setText("THÊM GIAO DỊCH");

        ma_ho_label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        ma_ho_label.setText("Mã hộ");

        ma_phi_label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        ma_phi_label.setText("Mã phí");

        ten_phi_label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        ten_phi_label.setText("Tên phí");

        ngay_nop_label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        ngay_nop_label.setText("Ngày nộp");

        ma_ho_field.setEditable(false);
        ma_ho_field.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ma_ho_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        so_tien_field.setEditable(false);
        so_tien_field.setBackground(new java.awt.Color(255, 255, 255));
        so_tien_field.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        so_tien_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        so_tien_label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        so_tien_label.setText("Số tiền cần nộp");

        ten_phi_field.setEditable(false);
        ten_phi_field.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ten_phi_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ma_phi_select_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ma_phi_select_button.setText("Chọn");
        ma_phi_select_button.setFocusable(false);
        ma_phi_select_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ma_phi_select_buttonActionPerformed(evt);
            }
        });

        ma_ho_select_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ma_ho_select_button.setText("Chọn");
        ma_ho_select_button.setFocusable(false);
        ma_ho_select_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ma_ho_select_buttonActionPerformed(evt);
            }
        });

        ma_phi_field.setEditable(false);
        ma_phi_field.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ma_phi_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ngayNopDateChooser.setDateFormatString("dd/MM/yyyy");
        ngayNopDateChooser.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        money_calc_button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        money_calc_button.setText("Tính phí");
        money_calc_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                money_calc_buttonActionPerformed(evt);
            }
        });

        themButton.setText("Thêm");
        themButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        themButton.setkBackGroundColor(new java.awt.Color(36, 193, 93));
        themButton.setkEndColor(new java.awt.Color(36, 193, 93));
        themButton.setkHoverEndColor(new java.awt.Color(36, 193, 93));
        themButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        themButton.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        themButton.setkPressedColor(new java.awt.Color(0, 51, 51));
        themButton.setkStartColor(new java.awt.Color(36, 193, 93));
        themButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themButtonActionPerformed(evt);
            }
        });

        huyButton.setText("Hủy");
        huyButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        huyButton.setkBackGroundColor(new java.awt.Color(102, 102, 102));
        huyButton.setkEndColor(new java.awt.Color(153, 153, 153));
        huyButton.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        huyButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        huyButton.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        huyButton.setkPressedColor(new java.awt.Color(153, 153, 153));
        huyButton.setkStartColor(new java.awt.Color(153, 153, 153));
        huyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyButtonActionPerformed(evt);
            }
        });

        ten_nguoi_dong_label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        ten_nguoi_dong_label.setText("Tên người đóng");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("(*)");

        ten_nguoi_dong_field.setBackground(new java.awt.Color(255, 255, 255));
        ten_nguoi_dong_field.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ten_nguoi_dong_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ten_nguoi_dong_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ten_nguoi_dong_fieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addGap(0, 242, Short.MAX_VALUE)
                .addComponent(themButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(huyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(so_tien_label)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ma_ho_label, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ma_phi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ngay_nop_label, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(tieu_de_label, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(so_tien_field, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                            .addComponent(ngayNopDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(money_calc_button))
                                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(ten_phi_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                            .addComponent(ma_phi_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                            .addComponent(ma_ho_field, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ma_phi_select_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ma_ho_select_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(ten_nguoi_dong_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ten_nguoi_dong_field, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ten_phi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(tieu_de_label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(ma_phi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ma_ho_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ma_ho_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ma_ho_select_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ma_phi_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ma_phi_select_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ten_phi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ten_phi_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ten_nguoi_dong_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(ten_nguoi_dong_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addComponent(so_tien_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(so_tien_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(money_calc_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ngay_nop_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngayNopDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(huyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(themButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void huyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huyButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_huyButtonActionPerformed

    private void themButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themButtonActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thêm không?");
        if (x == JOptionPane.YES_OPTION) {
            try {
                NopPhi nopPhi = new NopPhi();
                nopPhi.setMaHo(ma_ho_field.getText());
                nopPhi.setMaPhi(ma_phi_field.getText());
                nopPhi.setTenNguoiDong(ten_nguoi_dong_field.getText());
                nopPhi.setTenPhi(ten_phi_field.getText());
                DecimalFormat df = new DecimalFormat();
                df.setMaximumFractionDigits(340);
                nopPhi.setSoTien(df.parse(so_tien_field.getText()).doubleValue());
                java.util.Date ngayNop = ngayNopDateChooser.getDate();
                nopPhi.setNgayDong(new Date(ngayNop.getTime()));
                if (NopPhiController.themNopPhi(nopPhi)) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công!", "Thêm giao dịch", JOptionPane.INFORMATION_MESSAGE);
                    parentContext.loadThuPhiTable();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại!", "Thêm giao dịch", JOptionPane.ERROR_MESSAGE);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Thêm thất bại!", "Thêm giao dịch", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_themButtonActionPerformed

    private void money_calc_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_money_calc_buttonActionPerformed
        // TODO add your handling code here:
        String ma_ho = ma_ho_field.getText();
        String ma_phi = ma_phi_field.getText();
        DecimalFormat df = new DecimalFormat();
        df.setMaximumFractionDigits(340);
        if(ma_ho.length() != 0 && ma_phi.length() != 0)
        {
            so_tien_field.setText(String.valueOf(df.format(NopPhiDAO.getSoTienPhaiDong(ma_ho, ma_phi))));
        }
        else JOptionPane.showMessageDialog(null, "Hãy chọn đầy đủ mã hộ và mã phí!");
    }//GEN-LAST:event_money_calc_buttonActionPerformed

    private void ma_ho_select_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ma_ho_select_buttonActionPerformed
        // TODO add your handling code here:
        AddFee_SelectMaHoScreen.showScreen(this);
    }//GEN-LAST:event_ma_ho_select_buttonActionPerformed

    private void ma_phi_select_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ma_phi_select_buttonActionPerformed
        // TODO add your handling code here:
        AddFee_SelectMaPhiScreen.showScreen(this);
    }//GEN-LAST:event_ma_phi_select_buttonActionPerformed

    private void ten_nguoi_dong_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ten_nguoi_dong_fieldFocusLost
        // TODO add your handling code here:
        if (this.isVisible()) {
            String tenNguoiDong = ten_nguoi_dong_field.getText();
            if (tenNguoiDong.length() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Tên người đóng phí không được để trống");
            } else if(tenNguoiDong.length() > 100){
                JOptionPane.showMessageDialog(rootPane, "Tên người đóng phí không được quá 100 ký tự");
            }
        }
    }//GEN-LAST:event_ten_nguoi_dong_fieldFocusLost


    public static void showAddFee(MainScreen pContext) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NopPhiScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NopPhiScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NopPhiScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NopPhiScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NopPhiScreen(pContext).setVisible(true);
            }
        });
    }

    public JTextField getMa_ho_field() {
        return ma_ho_field;
    }

    public void setMa_ho_field(JTextField ma_ho_field) {
        this.ma_ho_field = ma_ho_field;
    }

    public JLabel getMa_ho_label() {
        return ma_ho_label;
    }

    public void setMa_ho_label(JLabel ma_ho_label) {
        this.ma_ho_label = ma_ho_label;
    }

    public JButton getMa_ho_select_button() {
        return ma_ho_select_button;
    }

    public void setMa_ho_select_button(JButton ma_ho_select_button) {
        this.ma_ho_select_button = ma_ho_select_button;
    }

    public JTextField getMa_phi_field() {
        return ma_phi_field;
    }

    public void setMa_phi_field(JTextField ma_phi_field) {
        this.ma_phi_field = ma_phi_field;
    }

    public JLabel getMa_phi_label() {
        return ma_phi_label;
    }

    public void setMa_phi_label(JLabel ma_phi_label) {
        this.ma_phi_label = ma_phi_label;
    }

    public JButton getMa_phi_select_button() {
        return ma_phi_select_button;
    }

    public void setMa_phi_select_button(JButton ma_phi_select_button) {
        this.ma_phi_select_button = ma_phi_select_button;
    }

    public JLabel getNgay_nop_label() {
        return ngay_nop_label;
    }

    public void setNgay_nop_label(JLabel ngay_nop_label) {
        this.ngay_nop_label = ngay_nop_label;
    }

    public JTextField getSo_tien_field() {
        return so_tien_field;
    }

    public void setSo_tien_field(JTextField so_tien_field) {
        this.so_tien_field = so_tien_field;
    }

    public JLabel getSo_tien_label() {
        return so_tien_label;
    }

    public void setSo_tien_label(JLabel so_tien_label) {
        this.so_tien_label = so_tien_label;
    }

    public JTextField getTen_phi_field() {
        return ten_phi_field;
    }

    public void setTen_phi_field(JTextField ten_phi_field) {
        this.ten_phi_field = ten_phi_field;
    }

    public JLabel getTen_phi_label() {
        return ten_phi_label;
    }

    public void setTen_phi_label(JLabel ten_phi_label) {
        this.ten_phi_label = ten_phi_label;
    }

    public JLabel getTieu_de_label() {
        return tieu_de_label;
    }

    public void setTieu_de_label(JLabel tieu_de_label) {
        this.tieu_de_label = tieu_de_label;
    }

    public JButton getMoney_calc_button() {
        return money_calc_button;
    }

    public void setMoney_calc_button(JButton money_calc_button) {
        this.money_calc_button = money_calc_button;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton huyButton;
    private javax.swing.JLabel jLabel11;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private javax.swing.JTextField ma_ho_field;
    private javax.swing.JLabel ma_ho_label;
    private javax.swing.JButton ma_ho_select_button;
    private javax.swing.JTextField ma_phi_field;
    private javax.swing.JLabel ma_phi_label;
    private javax.swing.JButton ma_phi_select_button;
    private javax.swing.JButton money_calc_button;
    private com.toedter.calendar.JDateChooser ngayNopDateChooser;
    private javax.swing.JLabel ngay_nop_label;
    private javax.swing.JTextField so_tien_field;
    private javax.swing.JLabel so_tien_label;
    private javax.swing.JTextField ten_nguoi_dong_field;
    private javax.swing.JLabel ten_nguoi_dong_label;
    private javax.swing.JTextField ten_phi_field;
    private javax.swing.JLabel ten_phi_label;
    private com.k33ptoo.components.KButton themButton;
    private javax.swing.JLabel tieu_de_label;
    // End of variables declaration//GEN-END:variables
}
